services:
  worker:
    build:
      context: ./server
      dockerfile: ./Dockerfile
      args:
        MAIN_PATH: ./cmd/worker
    env_file: .env
    environment:
      - DATABASE=/data/citadel/citadel.sqlite
      - TEMPORAL_HOST_PORT=temporal-server:7233
    volumes:
      - ./data/citadel:/data/citadel
    depends_on:
      - temporal-server
  api:
    build:
      context: ./server
      dockerfile: ./Dockerfile
      args:
        MAIN_PATH: ./cmd/api
    ports:
      - "4444:4444"
    env_file: .env
    environment:
      - DATABASE=/data/citadel/citadel.sqlite
      - TEMPORAL_HOST_PORT=temporal-server:7233
      - PORT=4444
      - CORS=http://localhost:3000
    volumes:
      - ./data/citadel:/data/citadel
    depends_on:
      - temporal-server
  fe:
    build:
      context: ./fe
      dockerfile: ./Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - VITE_API_HOST=http://localhost:4444
    volumes:
      - ./fe:/app
      - /app/node_modules
    depends_on:
      - api
  temporal-server:
    image: temporalio/temporal:latest
    ports:
      - "8233:8233"
    volumes:
      - ./data/temporal:/home/temporal
    command: server start-dev --ip 0.0.0.0 --db-filename /home/temporal/temporal.db
    restart: unless-stopped
