services:
  worker:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        MAIN_PATH: ./cmd/worker
    env_file: .env
    environment:
      - DATABASE=/data/citadel/citadel.sqlite
      - TEMPORAL_HOST_PORT=temporal-server:7236
    volumes:
      - ./data/citadel:/data/citadel
    depends_on:
      - temporal-server
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        MAIN_PATH: ./cmd/api
    ports:
      - "4444:4444"
    env_file: .env
    environment:
      - DATABASE=/data/citadel/citadel.sqlite
      - TEMPORAL_HOST_PORT=temporal-server:7236
      - PORT=4444
      - CORS=http://localhost:3000
    volumes:
      - ./data/citadel:/data/citadel
    depends_on:
      - temporal-server
  temporal-server:
    image: temporalio/server:1.28.0
    ports:
      - "7236:7236"
      - "7233:7233"
    environment:
      - DB=sqlite
      - DB_FILENAME=/etc/temporal/default.db
      - TEMPORAL_ADDRESS=0.0.0.0:7236
      - TEMPORAL_HTTP_PORT=7233
    volumes:
      - ./data/temporal:/etc/temporal
    restart: unless-stopped
  temporal-ui:
    image: temporalio/ui:2.39.0
    ports:
      - "8233:8233"
    environment:
      - TEMPORAL_ADDRESS=temporal-server:7236
    depends_on:
      - temporal-server
    restart: unless-stopped
