@host=http://localhost:4444

### Health check

GET /healthz

### Create a feed

POST /v1/feeds
Content-Type: application/json
{
    "url": "https://apenwarr.ca/log/rss.php"
}

### Get a feed

@id = {{$input input id?}}
GET /v1/feeds/{{id}}
