@agghost=http://localhost:4444
@timehost=http://localhost:4445

### Health check

GET /healthz

### Agg: Create a feed

POST {{agghost}}/v1/feeds
Content-Type: application/json
{
    "url": "https://apenwarr.ca/log/rss.php"
}

### Agg: Get a feed

@id = {{$input input id?}}
GET {{agghost}}/v1/feeds/{{id}}

### Agg: Get an entry

@id = {{$input input id?}}
GET {{agghost}}/v1/entries/{{id}}

### Timeline: Create a subscription

@user_id = {{$input input user_id?}}
@feed_id = {{$input input feed_id?}}
POST {{timehost}}/v1/users/{{user_id}}/subscriptions
Content-Type: application/json
{
    "feed_id": "{{feed_id}}"
}
