CREATE TABLE users (
	id TEXT PRIMARY KEY,
	github_id TEXT NOT NULL,
	email TEXT NOT NULL,
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
